#+TITLE: D3M Multitable Description
* About
This is a document to write about how to do multiple tables
with the D3M [[https://datadrivendiscovery.org/wiki/display/gov/Data+Annotation+Schema][dataSchema]] as in the example [[https://datadrivendiscovery.org/wiki/display/work/Kick-Off+Agenda?preview=%2F1867913%2F2818180%2FLincolnLabKickoff_SchemasAndDataInDepth_uploadVersion.pdf][in this presentation]].

* Description
In the dataSchema, there is a single dictionary that is
meant to handle multiple tables. Here, we have multiple
tables. Here's how that is read and annotated:

+ For ~trainData.csv~ there are variables that link to other tables.
+ In those variables can uniquely link to another file in
  the subdirectory ~/raw_data~. It would be reasonable to
  have a variable name ~parent_entity~ where every instance
  is ~parent_entity.csv~.
+ The next variable would then be something like
  ~parent_entity _id~ which indicates where to look in the
  linked table. 
+ In ~/raw_data/parent_entity~ there would be a variable
  named ~id~. Potentially many "children" from the variable
  ~parent_entity _id~ in trainData.csv would be matched to a
  single entry here.

* Notes on the json
Given that data representation, there is an open question as
to how to best notate it in ~dataSchema.json~. Our solution
is as follows:

+ (BIG QUESTION) Every variable, including those found only in
  ~/raw_data~, should be described with varName,
  varDescription as well as all of the ordinary information.
+ (QUESTION) d3mIndex should only be specified as the index
  of the associated table (trainData.csv, testData.csv etc), not any of the tables in
  ~/raw_data~.
+ Each ~parent_entity _id~ should have type index. Each
  ~parent_entity~ should have type file with
  ~varFileType=csv~.
+ dateTimes should not be used to link tables and should
  have Variable Role as metadata.
+ Variable names must conform to the convention ~entityName
  _identification~ so that a TA1 or TA2 system knows to
  check for the variable ~identification~ in the
  corresponding file from the variable ~entityName~.

 




